#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\deleted.bof
BOFS = palsy.bof dementia.bof firewand.bof SpecialWand.bof sickness.bof \
       breakrodpurge.bof breakrodhold.bof breakrodblind.bof hazarclasses.bof

!include $(KODDIR)\kod.mak
